spring:
  application:
    name: spreadsheet-generator
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/spreadsheet_generator}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  sql:
    init:
      mode: never

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
  show-actuator: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.filestreamer.spreadsheetgenerator: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
# Development profile
spring:
  config:
    activate:
      on-profile: development
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  flyway:
    enabled: true
  
  # DevTools configuration for hot reload
  devtools:
    restart:
      enabled: true
      # Exclude directories that don't need restart
      exclude: "static/**,public/**,templates/**,META-INF/maven/**,META-INF/resources/**"
      # Include additional paths to watch
      additional-paths: "src/main/java"
      # Faster restart trigger
      poll-interval: 1000
      quiet-period: 400
    livereload:
      enabled: true
      port: 35729

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  flyway:
    enabled: false

  h2:
    console:
      enabled: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: production
  
  jpa:
    show-sql: false
  
logging:
  level:
    com.filestreamer: INFO
    org.springframework.web: WARN 